// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7DtEa4WqA5-QVPYcgsTia_JUPC4KdBfs',
    appId: '1:737983686278:web:aba30fdc3e591516929307',
    messagingSenderId: '737983686278',
    projectId: 'technoexamportal',
    authDomain: 'technoexamportal.firebaseapp.com',
    storageBucket: 'technoexamportal.appspot.com',
    measurementId: 'G-10S4KT7D5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9SWGzbvv10VWkY9wULMZ3VuhXGTj0pDE',
    appId: '1:737983686278:android:3e0bb479744fdca7929307',
    messagingSenderId: '737983686278',
    projectId: 'technoexamportal',
    storageBucket: 'technoexamportal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASDjTJMIzmSdTTeWdWEpOuaqRYH1htAtw',
    appId: '1:737983686278:ios:5136297b0bae1415929307',
    messagingSenderId: '737983686278',
    projectId: 'technoexamportal',
    storageBucket: 'technoexamportal.appspot.com',
    iosClientId: '737983686278-kuea87pacdat5fhmodae5bb61ifstnq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiuexamportal',
  );
}
